<?php

/**
 * @file
 * Main file for Duration Formatter module.
 */


/**
 * Implements hook_field_formatter_info().
 */
function duration_formatter_field_formatter_info() {
  return array(
    'duration' => array(
      'label' => t('Duration'),
      'field types' => array('number_integer', 'number_decimal', 'number_float'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function duration_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  // This is where the output will be.
  $element = array();

  foreach ($items as $delta => $item) {
    // Getting field value.
    $value = $item['value'];

    $hours = intval(intval($value) / 3600);
    $minutes = intval(($value / 60) % 60);
    $seconds = intval($value % 60);

    $duration = '';

    if ($hours !== 0) {
      $duration = str_pad($hours, 2, '0', STR_PAD_LEFT). ':';
    }

    $duration .= str_pad($minutes, 2, '0', STR_PAD_LEFT). ':';
    $duration .= str_pad($seconds, 2, '0', STR_PAD_LEFT);

    $element[$delta] = array(
      '#markup' => $duration,
    );
  }

  return $element;
}
