<?php

/**
 * Main file for Duration Formatter module.
 */


/**
 * Implements hook_field_formatter_info().
 */
function duration_formatter_field_formatter_info() {
  return array(
    'duration' => array(
      'label' => t('Duration'),
      'field types' => array('number_integer', 'number_decimal', 'number_float'),
      // @TODO: Should we provide settings for the date parts?
      /*'settings' => array(
        'hours' => TRUE,
        'minutes' => TRUE,
        'seconds' => TRUE,
      ),*/
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function duration_formatter_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  // This gets the view mode where the settings are stored.
  $display = $instance['display'][$view_mode];
  // This gets the settings.
  $settings = $display['settings'];

  $element = array();

  // @TODO: See #16.

  /*$element['hours'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show hours'),
    '#default_value' => $settings['hours'],
  );

  $element['minutes'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show minutes'),
    '#default_value' => $settings['minutes'],
  );

  $element['seconds'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show seconds'),
    '#default_value' => $settings['seconds'],
  );*/

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function duration_formatter_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  // @TODO: See #16.
  $summary = '';

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function duration_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  // This is where the output will be.
  $element = array();
  // Store the field formatter settings.
  $settings = $display['settings'];

  foreach ($items as $delta => $item) {
    // Getting field value.
    $value = $item['value'];

    $hours = intval(intval($value) / 3600);
    $minutes = intval(($value / 60) % 60);
    $seconds = intval($value % 60);

    $duration = '';

    if ($hours !== 0) {
      $duration = str_pad($hours, 2, '0', STR_PAD_LEFT). ':';
    }

    $duration .= str_pad($minutes, 2, '0', STR_PAD_LEFT). ':';
    $duration .= str_pad($seconds, 2, '0', STR_PAD_LEFT);

    $element[$delta] = array(
      '#markup' => $duration,
    );
  }

  return $element;
}
